# Generated by Django 4.2.7 on 2023-12-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleterequest',
            name='requesting_time',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
