# Generated by Django 4.2.7 on 2023-12-02 08:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0005_deleterequest_requesting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleterequest',
            name='requesting_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
