# Generated by Django 4.2.7 on 2023-12-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0007_alter_deleterequest_requesting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleterequest',
            name='requesting_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
