# Generated by Django 4.2.7 on 2023-12-02 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0008_alter_deleterequest_requesting_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deleterequest',
            name='requesting_time',
        ),
    ]
