# Generated by Django 4.2.7 on 2023-12-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0009_remove_deleterequest_requesting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleterequest',
            name='requesting_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
